### ISSUE TITLE
error running build.py

### ISSUE THREAD

**Issue by danbroz** [colonelwatch/abstracts-search#1]
I love your code.  Unfortunately, I ran into the below error running bulid.py on Ubuntu server 22.04.3.  Thank you in advance.

(abstracts-search) dan@server0:~/abstracts-search$ python build.py
No works table found, starting works download...
work_urls:   0%|                                                                              | 0/501 [00:04<?, ?it/s]
Process Process-8:         
multiprocessing.pool.RemoteTraceback: 
"""ks_8: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/dan/anaconda3/envs/abstracts-search/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/dan/abstracts-search/build.py", line 83, in works_url_routine
    document = _build_document(row)
  File "/home/dan/abstracts-search/build.py", line 47, in _build_document
    return f'{row["title"]} {_recover_abstract(row["abstract_inverted_index"])}'
  File "/home/dan/abstracts-search/build.py", line 34, in _recover_abstract
    abstract_size = max([max(appearances) for appearances in inverted_index.values()])+1
  File "/home/dan/abstracts-search/build.py", line 34, in <listcomp>
    abstract_size = max([max(appearances) for appearances in inverted_index.values()])+1
TypeError: 'int' object is not iterable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dan/abstracts-search/build.py", line 162, in <module>
Traceback (most recent call last):
    for n_works in pool.imap(works_url_routine, args_iter):
  File "/home/dan/anaconda3/envs/abstracts-search/lib/python3.10/multiprocessing/pool.py", line 873, in next
  File "/home/dan/anaconda3/envs/abstracts-search/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/dan/anaconda3/envs/abstracts-search/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dan/abstracts-search/build.py", line 56, in model_routine
    documents, i_cpu = in_queue.get()
  File "<string>", line 2, in get
  File "/home/dan/anaconda3/envs/abstracts-search/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
    kind, result = conn.recv()
  File "/home/dan/anaconda3/envs/abstracts-search/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/dan/anaconda3/envs/abstracts-search/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/dan/anaconda3/envs/abstracts-search/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
    raise value
TypeError: 'int' object is not iterable

**Comment by colonelwatch** [comment]
I've seen this line fail when I was developing this project, but when I ran the finished thing over the entire OpenAlex snapshot a couple months ago, it didn't happen. Sounds like a new entry got added, and that caused it to fail again. I think it should be changed to just log a warning instead of straight-up failing like this, but the entry that's causing it to fail should also be investigated.

**Comment by danbroz** [comment]
I 100% agree.  Again thanks for writing this.

I found a fix for your code.  Adding 
["abstract_inverted_index"]["InvertedIndex"] 
where 
["abstract_inverted_index"] 
exists except for 
works_chunk['abstract_inverted_index']

**Comment by danbroz** [comment]
Actually, that's not working 100%.  Still debugging.

**Comment by danbroz** [comment]
Did you complain to them and have them change it back?  Your original code is working again.

**Comment by colonelwatch** [comment]
No, I was actually going to look into it today or tomorrow. If it's working for you, that's great. I'll also run it and see if I'm getting the bug or not.

**Comment by colonelwatch** [comment]
Oh, it looks like they *did* release a new snapshot yesterday. In the changelogs: "abstract inverted index is correct object in snapshot (InvertedIndex key removed)". So, someone found that `InvertedIndex` key you found and got rid of it.
